### ISSUE TITLE
Some tests are failing on windows 8.1 - command line -p/--profile

### ISSUE THREAD

**Issue by callicles** [mozilla/jpm#157]
Launched tests with npm test on the repo latest version - Firefox Nightly 34.0a1 (2014-08-29).

Here is the result:
```
jpm run
    V should not overwrite or delete xpi in current xpi (13210ms)
    -o/--overload
      V overloads the SDK if overload set and uses [path] if given (8839ms)
      V overloads the SDK if overload set and JETPACK_ROOT set (8810ms)
      V overloads the SDK with [path] if set over JETPACK_ROOT (8855ms)
      V does not overload if overload set and JETPACK_ROOT is not set (12496ms)
    -v/--verbose
      V logs out only console messages from the addon without -v (12877ms)
      V logs out everything from console with -v (12665ms)
      V logs errors without `verbose` (12832ms)
    -b/--binary <BINARY>
      V Uses specified binary instead of default Firefox (3176ms)
    --binary-args <CMDARGS>
      V Passes in additional arguments to Firefox (single) (3182ms)
      V Passes in additional arguments to Firefox (multiple) (3148ms)
    -p/--profile
      1) Passes in a relative profile path to Firefox with -profile
      2) Passes in a absolute profile path to Firefox with -profile
      V Passes in a profile name to Firefox with -P (3082ms)
      options passed to an add-on
        V run with only -v option (12875ms)
        V run with options should receive options (13617ms)
    SDK context
      V @loader/options#metadata loads in package.json (13010ms)
|
  jpm init
    V creates package.json with defaults (3003ms)
    V creates package.json with custom entries (3062ms)
    V sanitizes entries (2999ms)
    V copies in default index.js if it DNE (3068ms)
    V does not copy in default index.js if it exists (3175ms)
    V copies in default test-index.js if it DNE (3300ms)
    V does not copy in default test-index.js if it exists (3186ms)
    3) allows non-numeric version strings
\
  jpm xpi
    V creates a xpi of the cwd (4097ms)
\
  lib/profile
    V creates a profile and returns the path 
    V creates a profile with proper default preferences (Firefox) 
    V creates a profile with an addon installed when given a XPI unpacked (104ms)
    V creates a profile with an addon installed when given a XPI packed (44ms)

  lib/utils
    V getManifest() returns manifest in cwd() 
    V getManifest() returns null when no package.json found 
    V normalizeBinary() finds binary by accessing the registry on Windows (86ms)
    V normalizeBinary() uses env var when registry access fails on Windows (41ms)
    V normalizeBinary() default sets (non-windows) 
    V normalizeBinary() returns binary path if passed 
    V normalizeBinary() finds OSX's full path when given .app 
    V normalizeBinary() uses JPM_FIREFOX_BINARY if no path specified 
    V normalizeBinary() uses path over JPM_FIREFOX_BINARY if specified 
    V normalizeBinary() normalizes special names like: nightly, beta, etc... on Windows (38ms)
    V normalizeBinary() normalizes special names like: firefox, nightly, etc...(non-Windows) 
    hasAOMSupport
      V hasAOMSupport true for valid ranges 
      V hasAOMSupport false for invalid ranges 
      V hasAOMSupport false for unspecified min 
      V hasAOMSupport false for no engines field 
      V hasAOMSupport false for unpopulated engines field 
      V hasAOMSupport false for one valid and one invalid engine 

  lib/rdf
    defaults
      V uses default values when none specified 
    attributes
      V parses a correct ID 
      V passes in a version 
      V name uses `title` first 
      V name uses `name` after `title` 
      V homepageURL uses `homepage` 
      V unpack uses `unpack` 
      V description uses `description` 
      V creator uses `author` 
      V iconURL uses `icon` 
  V icon64URL uses `icon64` 
      V adds `translator` fields for each translator 
      V adds `contributor` fields for each contributor 
    author
      V handles `author` fields with 'name <email@address.com>' 
      V handles `author` fields with only an email address 
      V handles `author` field as an object with `name` field 
    engines
      V adds engine min/max from engine string for firefox 
      V adds engine min/max from engine string for fennec 
      V handles multiple engines specified 
      V replaces undefined max versions with asterisks 
  V replaces undefined min versions with asterisks 
      V creates default Firefox targetApplication if no engines defined 
      V creates default Firefox targetApplication if no engines field 

  lib/validate
    V Successfully validates a valid addon 
    V Fails with invalid ID 
    V Fails with no name 
    V Fails with no main or index.js 
    V Fails if main specified and DNE 
    V Fails if package.json cannot be parsed 
|
  lib/xpi
    V Zips up cwd's addon (83ms)
    V Zips and creates install.rdf/bootstrap.js for AOM-unsupported addons (186ms)
    V Does not litter AOM-unsupported files (86ms)
    V validates addon before zipping 
    V Does not zip up xpi files (68ms)
    V Does not zip up hidden files or test directory (187ms)
    V Does zip test directory for jpm test (203ms)
/

  80 passing (3m)
  3 failing

  1) jpm run -p/--profile Passes in a relative profile path to Firefox with -profile:
     Uncaught AssertionError: expected '-no-remote -profile .\\path\\to\\profile     \r\n' to include '-profile ".\\path\\to\\profile"'
  

  2) jpm run -p/--profile Passes in a absolute profile path to Firefox with -profile:
     Uncaught AssertionError: expected '-no-remote -profile /path/to/profile     \r\n' to include '-profile "/path/to/profile"'
  

  3) jpm init allows non-numeric version strings:
     Error: timeout of 20000ms exceeded
      at null.<anonymous> (C:\Users\Nicolas\Documents\Repos\jpm\node_modules\mocha\lib\runnable.js:175:14)
      at Timer.listOnTimeout [as ontimeout] (timers.js:110:15)



npm ERR! Test failed.  See above for more details.
npm ERR! not ok code 0
```

**Comment by callicles** [comment]
@erikvold Completely forgot about this, sorry, let's close it. 

I don't have the setup anymore and nobody else reported it.

**Comment by ncalexan** [comment]
Closed by request.
