### ISSUE TITLE
test failure jpm test addons simple-prefs

### ISSUE THREAD

**Issue by erikvold** [mozilla/jpm#302]
1) jpm test addons simple-prefs:
     Error: timeout of 20000ms exceeded. Ensure the done() callback is being called in this test.
      at null.<anonymous> (/Users/erikvold/github/jpm/node_modules/mocha/lib/runnable.js:170:19)
      at Timer.listOnTimeout (timers.js:110:15)

**Comment by erikvold** [comment]
Validating the manifest
Creating XPI
Created XPI at /var/folders/v2/pq4lfnjx0nj43h97ppl6dtcm0000gn/T/test-simple-prefs@jetpack.xpi
Shumway is registered
Running tests on Firefox 41.0a1/Gecko 41.0a1 (Build 20150515084717) ({ec8030f7-c20a-464f-9b0e-13a3a9e97384}) under darwin/x86_64.
console.info: undefined: executing './test/test-inline-prefs.testAOM'
console.log: undefined: [JavaScript Error: "TypeError: target.permanentKey is not a non-null object" {file: "resource:///modules/sessionstore/SessionStore.jsm" line: 816}]
console.log: undefined: [JavaScript Error: "NS_ERROR_FAILURE: Invalid view: detail" {file: "chrome://mozapps/content/extensions/extensions.js" line: 721}]
console.info: undefined: pass: the add-on prefs page was opened.
console.log: undefined: [JavaScript Warning: "This site makes use of a SHA-1 Certificate; it's recommended you use certificates with signature algorithms that use hash functions stronger than SHA-1." {file: "https://tiles.cdn.mozilla.net/images/1332a68badf11e3f7f69bf7364e79c0a7e2753bc.5316.png" line: 0}]
console.log: undefined: [JavaScript Warning: "This site makes use of a SHA-1 Certificate; it's recommended you use certificates with signature algorithms that use hash functions stronger than SHA-1." {file: "https://tiles.cdn.mozilla.net/images/d11ba0b3095bb19d8092cd29be9cbb9e197671ea.28088.png" line: 0}]
console.log: undefined: [JavaScript Warning: "This site makes use of a SHA-1 Certificate; it's recommended you use certificates with signature algorithms that use hash functions stronger than SHA-1." {file: "https://tiles.cdn.mozilla.net/images/1ddd27484ee94475bff83cf81d2bc50d7762508c.13811.png" line: 0}]
console.log: undefined: [JavaScript Warning: "This site makes use of a SHA-1 Certificate; it's recommended you use certificates with signature algorithms that use hash functions stronger than SHA-1." {file: "https://tiles.cdn.mozilla.net/images/942999d58ef3d83d0e8f88ad38f20dad1d498f39.3500.png" line: 0}]
console.log: undefined: [JavaScript Warning: "This site makes use of a SHA-1 Certificate; it's recommended you use certificates with signature algorithms that use hash functions stronger than SHA-1." {file: "https://tiles.cdn.mozilla.net/images/491c982f3af76207c5173b339ad8d9d1a9b68d0b.12826.png" line: 0}]
console.log: undefined: [JavaScript Warning: "This site makes use of a SHA-1 Certificate; it's recommended you use certificates with signature algorithms that use hash functions stronger than SHA-1." {file: "https://tiles.cdn.mozilla.net/images/642bd837527637cc05d3b3d4f452f7f243fba4bb.11109.png" line: 0}]
console.log: undefined: [JavaScript Warning: "This site makes use of a SHA-1 Certificate; it's recommended you use certificates with signature algorithms that use hash functions stronger than SHA-1." {file: "https://tiles.cdn.mozilla.net/images/fc5808feda7629b76d81c6296bfef5bd79793280.6225.png" line: 0}]
console.log: undefined: [JavaScript Warning: "This site makes use of a SHA-1 Certificate; it's recommended you use certificates with signature algorithms that use hash functions stronger than SHA-1." {file: "https://tiles.cdn.mozilla.net/images/1dc7720a2498b8f81ced9626894364c84a8f9a89.6364.png" line: 0}]
console.log: undefined: [JavaScript Warning: "This site makes use of a SHA-1 Certificate; it's recommended you use certificates with signature algorithms that use hash functions stronger than SHA-1." {file: "https://tiles.cdn.mozilla.net/images/e822cd4628c5162313f49f5d4556f8aafdf38750.11513.png" line: 0}]
console.log: undefined: [JavaScript Warning: "This site makes use of a SHA-1 Certificate; it's recommended you use certificates with signature algorithms that use hash functions stronger than SHA-1." {file: "https://tiles.cdn.mozilla.net/images/cc63774b7a9aae02fe36bc5caf90c1e25e66a2bc.13791.png" line: 0}]
console.log: undefined: [JavaScript Warning: "This site makes use of a SHA-1 Certificate; it's recommended you use certificates with signature algorithms that use hash functions stronger than SHA-1." {file: "https://tiles.cdn.mozilla.net/images/490d42d1f9a76c07739626d1b8a569169aec8fbe.11039.png" line: 0}]
console.log: undefined: [JavaScript Warning: "This site makes use of a SHA-1 Certificate; it's recommended you use certificates with signature algorithms that use hash functions stronger than SHA-1." {file: "https://tiles.cdn.mozilla.net/images/8acf9436e1b315f5f04b9435a518bcd1aef131f8.5663.png" line: 0}]
console.log: undefined: [JavaScript Warning: "This site makes use of a SHA-1 Certificate; it's recommended you use certificates with signature algorithms that use hash functions stronger than SHA-1." {file: "https://tiles.cdn.mozilla.net/images/40e5630405d5031ca73393bd7bc0064156f2cc82.10984.png" line: 0}]
console.log: undefined: [JavaScript Warning: "This site makes use of a SHA-1 Certificate; it's recommended you use certificates with signature algorithms that use hash functions stronger than SHA-1." {file: "https://tiles.cdn.mozilla.net/images/25c9fbb07308b84d160fc1b7959364a2c18f93b9.6404.png" line: 0}]
console.log: undefined: [JavaScript Warning: "This site makes use of a SHA-1 Certificate; it's recommended you use certificates with signature algorithms that use hash functions stronger than SHA-1." {file: "https://tiles.cdn.mozilla.net/images/877f1c561e735f7b9f419ff9ac79eb8c7481119d.16744.png" line: 0}]
console.log: undefined: [JavaScript Warning: "This site makes use of a SHA-1 Certificate; it's recommended you use certificates with signature algorithms that use hash functions stronger than SHA-1." {file: "https://tiles.cdn.mozilla.net/images/583de2b339502a7726bc05736a43b18e9c891350.2193.svg" line: 0}]
console.log: undefined: [JavaScript Warning: "This site makes use of a SHA-1 Certificate; it's recommended you use certificates with signature algorithms that use hash functions stronger than SHA-1." {file: "https://tiles.cdn.mozilla.net/images/720121e7462d8c7863b4dd8fa7b5c1089b5f5fb2.33862.png" line: 0}]
console.log: undefined: [JavaScript Warning: "This site makes use of a SHA-1 Certificate; it's recommended you use certificates with signature algorithms that use hash functions stronger than SHA-1." {file: "https://tiles.cdn.mozilla.net/images/b4adc58dd3c02da355104977b910255060cfd6d8.10350.png" line: 0}]
console.log: undefined: [JavaScript Warning: "This site makes use of a SHA-1 Certificate; it's recommended you use certificates with signature algorithms that use hash functions stronger than SHA-1." {file: "https://tiles.cdn.mozilla.net/images/d971cbafa0309a201e518acdac4f1ee4dabc7eaa.15109.png" line: 0}]
console.log: undefined: [JavaScript Warning: "This site makes use of a SHA-1 Certificate; it's recommended you use certificates with signature algorithms that use hash functions stronger than SHA-1." {file: "https://tiles.cdn.mozilla.net/images/068e0ccbd8701a28e2f078c640ee072b9a16e2e1.12490.png" line: 0}]
console.log: undefined: [JavaScript Warning: "This site makes use of a SHA-1 Certificate; it's recommended you use certificates with signature algorithms that use hash functions stronger than SHA-1." {file: "https://tiles.cdn.mozilla.net/images/22fb856cd58365855eb725b1565f08a72464e039.18717.png" line: 0}]
console.log: undefined: [JavaScript Error: "TypeError: browser(...) is undefined" {file: "resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/tabs/tab-firefox.js" line: 207}]
console.error: undefined: 
  fail:
  Timed out (after: the add-on prefs page was opened.)
console.error: undefined: 
  fail:
  Should not be any unexpected tabs open
console.trace: undefined: 
_ecated/unit-test.js 108 fail
_ecated/unit-test.js 340 done/<
_/Promise-backend.js 867 Handler.prototype.process
_/Promise-backend.js 746 this.PromiseWalker.walkerLoop
_/Promise-backend.js 688 this.PromiseWalker.scheduleWalkerLoop/<
                     0 

console.log: undefined: Windows open:
console.log: undefined: chrome://browser/content/browser.xul - about:blank, about:addons
console.info: undefined: executing './test/test-inline-prefs.testAgainstDocCaching'
console.log: undefined: [JavaScript Error: "TypeError: target.permanentKey is not a non-null object" {file: "resource:///modules/sessionstore/SessionStore.jsm" line: 816}]
console.info: undefined: pass: the add-on prefs page was opened.
console.log: undefined: [JavaScript Error: "TypeError: browser(...) is undefined" {file: "resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/tabs/tab-firefox.js" line: 207}]
console.error: undefined: 
  fail:
  Timed out (after: the add-on prefs page was opened.)
console.error: undefined: 
  fail:
  Should not be any unexpected tabs open
console.trace: undefined: 
_ecated/unit-test.js 108 fail
_ecated/unit-test.js 340 done/<
_/Promise-backend.js 867 Handler.prototype.process
_/Promise-backend.js 746 this.PromiseWalker.walkerLoop
_/Promise-backend.js 688 this.PromiseWalker.scheduleWalkerLoop/<
                     0 

console.log: undefined: Windows open:
console.log: undefined: chrome://browser/content/browser.xul - about:blank, about:addons
console.info: undefined: executing './test/test-inline-prefs.testButton'
console.log: undefined: [JavaScript Error: "TypeError: target.permanentKey is not a non-null object" {file: "resource:///modules/sessionstore/SessionStore.jsm" line: 816}]
console.log: undefined: [JavaScript Error: "TypeError: browser(...) is undefined" {file: "resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/tabs/tab-firefox.js" line: 207}]
console.error: undefined: 
  fail:
  Timed out (after: START)
console.error: undefined: 
  fail:
  Should not be any unexpected tabs open
console.trace: undefined: 
_ecated/unit-test.js 108 fail
_ecated/unit-test.js 340 done/<
_/Promise-backend.js 867 Handler.prototype.process
_/Promise-backend.js 746 this.PromiseWalker.walkerLoop
_/Promise-backend.js 688 this.PromiseWalker.scheduleWalkerLoop/<
                     0 

console.log: undefined: Windows open:
console.log: undefined: chrome://browser/content/browser.xul - about:blank, about:addons
console.info: undefined: executing './test/test-inline-prefs.testDefaultPreferencesBranch'
console.info: undefined: pass: preferencesBranch default the same as self.id
console.info: undefined: executing './test/test-inline-prefs.testDefaultValues'
console.info: undefined: pass: myHiddenInt default is 5
console.info: undefined: pass: myInteger default is 8
console.info: undefined: pass: somePreference default is correct
console.info: undefined: executing './test/test-inline-prefs.testOptionsType'
console.info: undefined: pass: options type is inline

7 of 13 tests passed.
There were test failures...

The following tests failed:
  ./test/test-inline-prefs.testAOM: timed out, failure
  ./test/test-inline-prefs.testAgainstDocCaching: timed out, failure
  ./test/test-inline-prefs.testButton: timed out, failure
