### ISSUE TITLE
--profile does not create profile if it doesn't exist

### ISSUE THREAD

**Issue by birjolaxew** [mozilla/jpm#323]
As described [on jpm's wiki page](https://developer.mozilla.org/en-US/Add-ons/SDK/Tools/jpm#Using_profiles_2):

> If you supply --profile but its argument is not the name of or path to an existing profile, jpm will open the profile manager,  enabling you to select and existing profile or create a new one:

Yet running `jpm run --profile i-dont-exist` results in:

    jfagerberg@laptop:~/test$ jpm run --profile i-dont-exist
    JPM undefined Starting jpm run on Test
    Creating XPI
    JPM undefined XPI created at /tmp/@test-1.0.0.xpi (357ms)
    Created XPI at /tmp/@test-1.0.0.xpi
    JPM undefined Copying provided profile:
    Potentially unhandled rejection [1] Error: cannot find profile i-dont-exist
        at findInProfiles (/usr/lib/node_modules/jpm/node_modules/firefox-profile/lib/profile_finder.js:83:62)
        at /usr/lib/node_modules/jpm/node_modules/firefox-profile/lib/profile_finder.js:88:7
        at /usr/lib/node_modules/jpm/node_modules/firefox-profile/lib/profile_finder.js:62:5
        at fs.js:334:14
        at FSReqWrap.oncomplete (fs.js:95:15)

Which ends the process.

**Comment by sblask** [comment]
Not sure whether this should be here or in a different issue, but even if you have an existing profile, it doesn't seem to be used properly. At least, it doesn't restore my tabs. Settings seem to be preserved though.

**Comment by ge0rgi** [comment]
@sblask Same here restore tabs setting is ignored and reseted to emtpy page

**Comment by sigmike** [comment]
Cookies do not seem to be saved in the profile either. Actually nothing is changed in the provided profile dir after run.

**Comment by gregglind** [comment]
(In `cfx` it created or re-used the profile.  the behaviour I want for 

`--profile ./something  --no-copy`

is:

- create it there if it doesn't exist
- re-use it if so.

This is needful for things where we need to test non-install behaviours (for testing orientations, 2nd startup, post-crash conditions, etc.)

I think it's moderate change to `jpm.js` and `profile.js`
